          - name: Install and Build
            run: |
              npm install
              # Usamos el nombre 'my-store' que está en tu angular.json
              npx ng build --configuration production --base-href /MyStore/

          - name: Deploy
            uses: JamesIves/github-pages-deploy-action@v4
            with:
              # Esta es la ruta exacta basada en tu configuración
              folder: dist/my-store/browser
              branch: gh-pages
